/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a adaptors -p interfaces -v dbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "interfaces.hpp"
#include "config.hpp"
#include <wntr/ipc.hpp>

namespace Wintermute {
    namespace Data {
    NodeInterface::NodeInterface() :
        QDBusAbstractInterface(WNTRDATA_DBUS_SERVICE, "/Nodes", staticInterfaceName(), *IPC::System::bus(), IPC::System::instance()) { }

    NodeInterface::~NodeInterface() { }

    RuleInterface::RuleInterface() :
        QDBusAbstractInterface(WNTRDATA_DBUS_SERVICE, "/Rules", staticInterfaceName(), *IPC::System::bus(), IPC::System::instance()) { }

    RuleInterface::~RuleInterface() { }

    SystemInterface::SystemInterface() :
        QDBusAbstractInterface(WNTRDATA_DBUS_SERVICE, "/System", staticInterfaceName(), *IPC::System::bus(), IPC::System::instance()) { }

    SystemInterface::~SystemInterface() { }
    }
}
