/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbus.xml -p interfaces -a adaptors
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "interfaces.hpp"

using namespace Wintermute::Data;

/*
 * Implementation of interface class OrgThesiiWintermuteDataNodesInterface
 */

NodeInterface::NodeInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NodeInterface::~NodeInterface()
{
}

/*
 * Implementation of interface class OrgThesiiWintermuteDataRulesInterface
 */

RuleInterface::RuleInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

RuleInterface::~RuleInterface()
{
}

/*
 * Implementation of interface class OrgThesiiWintermuteDataSystemInterface
 */

SystemInterface::SystemInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

SystemInterface::~SystemInterface()
{
}

